import Head from 'next/head'
import Sobremi from '@/components/Sobremi'
import Frameworks from '@/components/Frameworks'
import Perfil from '@/components/Perfil';
import Contacto from '@/components/Contacto'
import Titulo from '@/components/Titulo'
import Toolbar from '@/components/Toolbar'
import ThemeContext from "@/components/Themecontext"
import { useState } from 'react';
export default function Home() {
  type ThemeContextType = "light" | "dark";

  const [theme, setTheme] = useState<ThemeContextType>("light");
  return (
    <>
      <Head>
        <title>Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<section className='bubble'>
      <div className='container'>
        <Perfil />
    <ThemeContext.Provider value={theme}>
      <Toolbar/>
    </ThemeContext.Provider>
        <Titulo />
        <Sobremi />
        <Contacto />
        <Frameworks />
      </div>
</section>
    </>
  )
}
